dhis2/dhis2-releases

README.md
android-releases/2.1/ReleaseNote-2.1.0.md
android-releases/2.1/ReleaseNote-2.1.1.md
android-releases/2.1/ReleaseNote-2.1.2.md
android-releases/2.2/ReleaseNote-2.2.0.md
android-releases/2.2/ReleaseNote-2.2.1.md
android-releases/2.2/ReleaseNote-2.2.2.md
android-releases/2.3/ReleaseNote-2.3.0.md

Adding android releases info from 2.1, 2.2 and 2.3.
Updated README

chore: Add Android relases info

---

releases/2.36/README.md

In connection with https://github.com/dhis2/dhis2-core/pull/7320

add a bullet on added shortName column for Category, DataElementGroupSet, OrganisationUnitGroupSet

---

releases/2.36/README.md

This is covering a few attributes that were refactored/modified in the Visualizations API.

feat: Release notes related to DHIS2-10054

---

releases/2.37/ReleaseNote-2.37.md

Adds features that have been completed within the 2.37 development phase.

docs(platform): add platform features for 2.37

---

android-releases/2.5/ReleaseNote-2.5.0.md

I made some small grammar and spelling corrections while adding this text to the website.

Proofreading edits

---

releases/2.37/ReleaseNote-2.37.md

Added redesigned Icon Library to Platform Library section.

Update Release Notes - Icon Library

---

android-releases/2.5/ReleaseNote-2.5.0.md
android-releases/2.5/Roadmap-2.5.md

Final Release notes for Android Capture App 2.5

Release Notes Android 2.5

---

roadmap/platform.md

This is incomplete, @larshelge can help with the remaining items

chore: update Platform roadmap

---

releases/2.38/README.md

In relation to changes made in https://github.com/dhis2/dhis2-core/pull/9844

docs: removal of /systemSettings returning JSONP [DHIS2-12516]

---

releases/2.38/ReleaseNote-2.38.md

I noticed a few features that PEPFAR folks worked on weren't in the release notes yet, so I figured I'd add some draft text as a PR.  I hope it helps!

Added some features PEPFAR folks worked on

---

android-releases/2.6/ReleaseNote-2.6.0.md

Release notes for Android App 2.6

Adding Android App 2.6 Release Notes

---

roadmap/android.md

Mmvila patch 1

---

releases/deprecated-features.md

See changes in https://github.com/dhis2/dhis2-core/pull/13605 and https://github.com/dhis2/dhis2-core/pull/13654

Adds deprecation notice for organisation unit object parameters returning a list [DHIS2-13901]

---

releases/2.41/README.md

document deprecated tracker APIs from https://dhis2.atlassian.net/browse/TECH-1536

docs: document deprecated tracker APIs for 2.41

---

releases/2.41/README.md

see https://github.com/dhis2/dhis2-core/pull/14145

docs: document removal of attachment query parameter

---

releases/2.41/README.md

see https://github.com/dhis2/dhis2-core/pull/14153

docs: add keys for trackedEntity, enrollment, event object counts TECH-1551

---

releases/2.41/README.md

for
* https://github.com/dhis2/dhis2-core/pull/14591
* https://github.com/dhis2/dhis2-core/pull/14608

docs: deprecation notice for TECH-1581

---

releases/2.41/README.md

Create a section for Database breaking changes for :
- https://dhis2.atlassian.net/browse/TECH-1542
- https://dhis2.atlassian.net/browse/TECH-1593
- https://dhis2.atlassian.net/browse/TECH-1594

chore: Update release notes for [ TECH-1542 ] [TECH-1593 ] [ TECH-1594 ]

---

releases/2.41/README.md

release note for `trackedentitycomment` to `note` breaking change

refactor: rename trackedentitycomment to note [TECH-1614]

---

releases/2.41/README.md

Update reelase notes for removed parameters in TrackedEntity exporter

docs: Update release notes for removed parameters [DHIS2-15665]

---

releases/2.41/README.md

for https://github.com/dhis2/dhis2-core/pull/16164

docs: pagination fields in page objects in tracker exporter TECH-1679

---

releases/2.41/README.md

for https://github.com/dhis2/dhis2-core/pull/16196

docs: deprecate skipPaging in favor of paging in tracker exporter TECH-1678

---

releases/2.41/README.md

for changes
- https://dhis2.atlassian.net/browse/TECH-1681
- https://dhis2.atlassian.net/browse/TECH-1683
- https://dhis2.atlassian.net/browse/TECH-1684

docs: tracker pagination API TECH-1681 TECH-1683 TECH-1684

---

releases/2.41/README.md

Changes to document TEAs updates for analytics

docs: Update README.md

---

releases/2.41/README.md

https://dhis2.atlassian.net/browse/DHIS2-16165

fix: remove attachment request parameter

---

releases/2.41/README.md

Document the breaking change in the resource tables in analytics.

refactor: Prefix of analytics resource tables

---

releases/2.41/README.md

https://dhis2.atlassian.net/browse/DHIS2-16579
I'd stick with a simple description of scripts or views without going into much detail about what a user could do

Provide migration guidance for SQL views

---

README.md

ci: test pr merge workflow (not included path)

---

downloads/v1/versions/stable.json

ci: test pr merge workflow (included path)

---

releases/2.42/migration-notes.md

Add detailed information on how to detect the issue that lead to a failure in the migration and some ways to fix it

docs: Add migration notes [DHIS2-12600]

---

releases/2.42/README.md

for https://github.com/dhis2/dhis2-core/pull/19983

chore: add deprecated /tracker/ownership/transfer parameter DHIS2-19037

---

releases/2.42/ReleaseNote-2.42.md

This PR fixes spelling and grammar issues in the 42 version release notes.

fix: 42 release note spelling and grammar
